### ISSUE TITLE
saveImage function saves png file as jpeg file

### ISSUE THREAD

**Issue by berkayyildiz** [steveruizok/arrows-playground#1]
At App.tsx, saveImage function gets png from htmlToImage with toPng but saves returned dataUrl with "Download.jpg" name. This causes following error in some image wiewers: Not a JPEG file: starts with 0x89 0x50.

**Comment by steveruizok** [comment]
Good catch! Resolved by https://github.com/steveruizok/arrows-playground/commit/138140f713156a7d20899592c438b55da10337f3.
